### ISSUE TITLE
No longer working on Linux

### ISSUE THREAD

**Issue by DavidBuchanan314** [DavidBuchanan314/Turbo-Recadmiumator#1]
The patches install successfully, but media still plays at 720p. I need to figure out why...

Is it still working for people on other platforms?

**Comment by tianxuanzhizi** [comment]
> The patches install successfully, but media still plays at 720p. I need to figure out why...
> 
> Is it still working for people on other platforms?

nope,doesn't work on win 10，either

**Comment by DavidBuchanan314** [comment]
Fixed in 859fe71066510500cd7c8923fd785044431723f6
