### ISSUE TITLE
how do i use this? (tech noob)

### ISSUE THREAD

**Issue by ComfortableMilk4454** [DavidBuchanan314/Turbo-Recadmiumator#11]
<img width="1624" alt="image" src="https://github.com/DavidBuchanan314/Turbo-Recadmiumator/assets/43555540/5ae737cb-6593-4847-9546-8f8650e85834">
idk how to use this extension, what settings do i put for the best quality? thanks so much for making this extension btw, thank god there is a working netflix 1080p extension now that https://github.com/vladikoff/netflix-1080p-firefox doesn't work anymore. thanks for making this!

**Comment by ComfortableMilk4454** [comment]
also, i pressed reset and i dont see that popup anymore when i play a video. how do i invoke it again?

**Comment by k939kk** [comment]
Press Ctrl+Shift+Alt+B to bring up the bitrate selection menu again.

Also note, if you want the extension to automatically choose the best bitrate for you, then change the flag `set_max_bitrate` in cadmium-playercore...js to **false**. (a bit counter-intuitive, it is what it is)

If you want to select it yourself you can always press the keyboard shortcut.

If you want the bitrate menu to popup everytime to do it manually then set the flag `set_max_bitrate` to **true**

Please also go through the README.

**Comment by ComfortableMilk4454** [comment]
hi sorry for the late response. ive gone through the readme but i cant do Ctrl+Shift+Alt+B cuz im on a mac. also, how do i "change the flag set_max_bitrate in cadmium-playercore...js to false"? thanks so much

**Comment by k939kk** [comment]
> hi sorry for the late response. ive gone through the readme but i cant do Ctrl+Shift+Alt+B cuz im on a mac. also, how do i "change the flag set_max_bitrate in cadmium-playercore...js to false"? thanks so much

i am on a mac too. and it works. you have to press all the keys together ctrl+shift+option/alt+B. 
To change the flag, open the cadmium.js file in your favorite plain text editor.
