### ISSUE TITLE
feature request: packaging extension into a tampermonkey userscript

### ISSUE THREAD

**Issue by ComfortableMilk4454** [DavidBuchanan314/Turbo-Recadmiumator#12]
hi. i love this extension, but on firefox release 125.0.1 with xpinstall.signatures.required set to false in about:config it doesnt work, so im wondering if this could be made into a userscript (i saw davidbuchanan314 [mention in a github issue](https://github.com/DavidBuchanan314/Turbo-Recadmiumator/issues/4#issuecomment-2010917864) that they were considering doing that) so that it can be used on ff release and not just dev edition & esr. please let me know your thoughts! have a great one :)

**Comment by DavidBuchanan314** [comment]
@DavidBuchanan314 is me, so my thoughts are "very good idea, well done David". If someone wants to take a shot at it I am likely to accept the PR, but I don't have the time to work on it myself right now.

I'd like it to support Safari, Firefox, Chrome, and Edge (across MacOS, Windows, Linux, where applicable)

(actually I can't remember if we support Safari at all as-is, maybe I don't care about that lol)

**Comment by ComfortableMilk4454** [comment]
yeah ik ur the dev behind the project :). sounds good! i would try to make it into a userscript if i could but i havent the slightest clue how lol. lets hope someone else does! have a great one and thanks again for this awesome project!
