### ISSUE TITLE
Since mid-July 2024, extension doesn't work

### ISSUE THREAD

**Issue by 22raider** [DavidBuchanan314/Turbo-Recadmiumator#16]
Since about two weeks ago (since mid-July 2024), the extension does not work in Firefox. Well, actually, neither this extension nor the one from TheGoddessInari (which I used as an alternative) does not work. I have tried them on several different computers and with different versions of Firefox, but to no avail. It is as if the extensions are not installed at all. In Chrome, the jangxx extension and the truedread classic still work without problems.

**Comment by DavidBuchanan314** [comment]
I thought the latest update fixed this

**Comment by 22raider** [comment]
Thank you very much for the update. I just downloaded the updated files and created the new extension and it works correctly. Indeed, and as you describe, I think the problem was in the updated Netflix URLs.
